[package]
name = "bevy-poc"
version = "0.1.0"
edition = "2021"

[lib]
name = "bevy_poc"
path = "src/lib.rs"

[[bin]]
name = "bevy-poc"
path = "src/main.rs"

[[bin]]
name = "step1_skybox"
path = "src/bin/step1_skybox.rs"

[[bin]]
name = "step2_grid"
path = "src/bin/step2_grid.rs"

[[bin]]
name = "step3_skysun"
path = "src/bin/step3_skysun.rs"

[features]
legacy = []

[profile.test]
opt-level = 2

[dependencies]
bevy = { version = "0.18", features = ["3d", "bevy_remote"] }
bevy_egui = "0.39"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
smallvec = "1.13"
